"""Build preview.html: the game with the Matter CDN swapped for a local
copy, web fonts stripped, and a window.__pg test hook appended."""
import re
s = open('planet-genesis.html', encoding='utf-8').read()
s = s.replace('https://cdnjs.cloudflare.com/ajax/libs/matter-js/0.19.0/matter.min.js', 'matter.min.js')
s = re.sub(r'<link[^>]*fonts\.(googleapis|gstatic)\.com[^>]*>', '', s)
# The suites were written on the 4800 x 2400 map and their scenes sit where
# that map's floor was; tenv.js pins every suite page to it through these
# two keys (pg_test_world_w / _h) unless pg_test_real_world is set. The
# shipping file has no such switch: it is rewritten into the preview only.
WORLD_LINE = 'var WORLD_W = 19200, WORLD_H = 9600;'
assert WORLD_LINE in s, 'the world size line moved'
s = s.replace('var pads = navigator.getGamepads ? navigator.getGamepads() : null;', 'var pads = window.__pgFakePads ? window.__pgFakePads : (window.__pgFakePad !== undefined ? [window.__pgFakePad] : (navigator.getGamepads ? navigator.getGamepads() : null));')   # the suites plant a pad, or several
s = s.replace(WORLD_LINE, "var WORLD_W = +localStorage.getItem('pg_test_world_w') || 19200, WORLD_H = +localStorage.getItem('pg_test_world_h') || 9600;")
HOOK = """
  window.__pg = {
    objects: function(){ return objects; },
    G: { pgArea:pgArea, pgVertexCount:pgVertexCount, pgBounds:pgBounds, pgContains:pgContains },
    cam: function(){ return { x:camX, y:camY, s:camScale }; },
    w2s: worldToScreen,
    w2sPage: function(x, y){ var q = worldToScreen(x, y), r = canvas.getBoundingClientRect(); return { x: q.x + r.left, y: q.y + r.top }; },
    setTool: function(t){ currentTool = t; canvas.dataset.tool = t; },
    setLayer: function(l){ buildLayer = l; },
    setBrush: function(v){ paintScale = v; },
    setBrushShape: function(sh){ paintShape = sh; },
    setPaintMode: function(m){ paintMode = m; },
    setStick: function(v){ stickPaint = !!v; },
    freezeCam: function(){ camFollow = false; },
    zoomTo: function(z, x, y){ camFollow = false; camZoom = z; applyCamScale(); camX = x - viewRectW/camScale/2; camY = y - viewRectH/camScale/2; clampCamNow(); },
    setMode: setMode, mode: function(){ return mode; },
    load: loadLevelData, serialize: serializeLevel, autosave: autosaveNow,
    charState: function(){ return { crouching: crouching, sliding: sliding, anim: charPoseId() }; },
    setPaintAlpha: function(v){ paintAlpha = v; },
    stickerDraft: function(){ openStickerDraft(); return !charEditorOverlay.hidden; },
    matDraft: function(){ openMaterialDraft(); return !charEditorOverlay.hidden; },
    savedObjects: function(){ return savedObjects.map(function(s){ return { id: s.id, name: s.name }; }); },
    saveSelectedAs: function(name){ var group = selList(); if (!group.length) return false; var rec = buildSavedObject(group); rec.id = "u" + Date.now(); rec.name = name; savedObjects.push(rec); persistSavedObjects(); return true; },
    emitterUse: function(id, savedId){ var g = gadgetById(id), sv = savedObjects.find(function(s){ return s.id === savedId || s.name === savedId; }); if (!g || !sv) return false; g.emit = captureSavedObject(sv); g.ammoDef = null; return true; },
    mySaved: function(kind){ return (mySkins[kind] || []).map(function(e){ return { id: e.id, name: e.name, hasHit: !!(e.data && e.data.hitbox && e.data.hitbox.length), hasWeak: !!(e.data && e.data.weakD && e.data.weakD.length) }; }); },
    saveThing: function(id, name){ var g = gadgetById(id); if (!g) return false; if (!mySkins[g.kind]) mySkins[g.kind] = []; mySkins[g.kind].push({ id: "s" + Date.now(), name: name, data: packDrawnThing(g) }); persistMySkins(); return true; },
    placeSaved: function(kind, entryId){ var e = (mySkins[kind] || []).find(function(x){ return x.id === entryId; }); if (!e) return false; placePreset = { kind: kind, entry: e }; currentTool = kind; canvas.dataset.tool = kind; return true; },
    playHere: function(){ playFromHere(); return mode; },
    players: function(){ return players.map(function(P){ var b = P === me ? player : P.player; return { id: P.id, slot: P.slot, pad: P.pad, keyboard: P.keyboard, keyboard2: !!P.keyboard2, bound: P === me, x: b ? b.position.x : null, y: b ? b.position.y : null, bubble: P.bubble ? { x: P.bubble.x, y: P.bubble.y } : null, flying: P === me ? flying : P.flying, grounded: P === me ? grounded : P.grounded, armed: !!(P === me ? playerGun : P.playerGun), color: P === me ? charColor : P.charColor, scale: P === me ? charScale : P.charScale, carrying: !!(P === me ? carried : P.carried), hanging: !!(P === me ? grabConstraint : P.grabConstraint) }; }); },
    fakePads: function(list){ window.__pgFakePads = list; },
    charData: function(){ return currentCharacterData(); },
    wearChar: function(d){ applyCharacterData(d); return currentCharacterData().mode; },
    charGun: function(g){ if (g !== undefined){ charGun = normalizeCharGun(g); persistCharGun(); } return charGun; },
    poseId: function(){ return charPoseId(); },
    hitCrouch: function(strokes){ if (strokes !== undefined) setCharHitCrouch(strokes); return charHitCrouch; },
    playerBox: function(){ return player ? { w: PW, h: PH, crouching: crouching, verts: player.parts.length > 1 ? player.parts.length - 1 : 1, bounds: { x: player.bounds.min.x, y: player.bounds.min.y, x2: player.bounds.max.x, y2: player.bounds.max.y } } : null; },
    levelChars: function(v){ if (v !== undefined) worldSettings.chars = normalizeLevelChars(v); return JSON.parse(JSON.stringify(levelChars())); },
    addLevelChar: function(name, data){ var c = levelChars(); c.list.push({ id: "lc" + Date.now() + c.list.length, name: name, data: JSON.parse(JSON.stringify(data)) }); return c.list.length; },
    pick: function(){ return charPick ? { player: charPick.P.id, idx: charPick.idx, open: !charPickOverlay.hidden, cards: Array.from(document.querySelectorAll('#charPickCards .typeCard')).map(function(b){ return { name: b.querySelector('.tl').textContent, taken: b.disabled, active: b.classList.contains('active') }; }) } : null; },
    wearing: function(){ return players.map(function(P){ return { id: P.id, levelChar: P.levelChar == null ? null : P.levelChar, own: !!P.ownChar, color: P === me ? charColor : P.charColor, mode: P === me ? charMode : P.charMode, scale: P === me ? charScale : P.charScale, armed: !!(P === me ? playerGun : P.playerGun), gunFrom: (P === me ? playerGun : P.playerGun) ? (P === me ? playerGun : P.playerGun).from : null }; }); },
    tracks: function(){ return tracks.map(function(t){ return { id: t.id, gap: SEAT_GAP, n: t.pts.length, len: Math.round(trackLen(t)), seats: t.seats, pace: t.pace, look: !!t.look, s: Math.round(t.s), v: +t.v.toFixed(2), state: t.state, riders: t.riders.map(function(P){ return P.id; }), layer: t.layer, start: t.pts[0], end: t.pts[t.pts.length - 1], seat0: seatPos(t, 0) }; }); },
    addTrack: function(pts, layer){ var t = addTrack(pts.map(function(q){ return { x: q[0], y: q[1] }; }), layer); return t ? t.id : null; },
    trackSet: function(i, props){ var t = tracks[i]; if (!t) return false; for (var k in props) t[k] = props[k]; if (t.state === "wait") t.s = trainStart(t); return true; },
    selectTrack: function(i){ if (tracks[i]){ selectTrack(tracks[i]); opWanted = true; renderSelBar(); } return !!selectedTrack; },
    riding: function(){ return me && me.riding ? { track: me.riding.id, seat: me.seat } : null; },
    board: function(){ return boardCoaster(); },
    hopOff: function(){ return leaveCoaster(true); },
    useKey: function(){ return useLever(); },
    addBubble: function(x, y){ bubbles.push({ x: x, y: y, collected: false }); return bubbles.length; },
    score: function(){ return score; },
    gravityY: function(){ return engine.gravity.y; },
    look: function(){ return me ? me.lookAng : null; },
    bodyKind: function(){ return player ? (player.circleRadius ? "disc" : "box") : null; },
    pvp: function(){ return players.map(function(P){ return { slot: P.slot, kos: P.kos || 0, dead: P.dead || 0, lives: P.livesLeft, out: !!P.out, group: (P === me ? player : P.player) ? (P === me ? player : P.player).collisionFilter.group : null }; }); },
    playersHud: function(){ var el = document.getElementById("playersHud"); return el.hidden ? null : Array.from(el.children).map(function(c){ return c.textContent; }); },
    fireAt: function(i, x, y){ withPlayer(players[i], function(){ gunLastShot = 0; gunFire({ x: x, y: y }); }); },
    armAll: function(){ var g = gadgets.filter(function(q){ return q.kind === "gun"; })[0]; if (!g) return false; forEachPlayer(function(){ armPlayer(g); }); return true; },
    addPlayer: function(pad){ var P = addPlayer(pad); return P ? P.id : null; },
    removePlayer: function(i){ if (players[i]) removePlayer(players[i]); return players.length; },
    playerTo2: function(i, x, y){ withPlayer(players[i], function(){ Body.setPosition(player, { x: x, y: y }); Body.setVelocity(player, { x: 0, y: 0 }); }); },
    bubble: function(i){ withPlayer(players[i], function(){ bubbleUp(); }); return !!players[i].bubble; },
    padState: function(){ return { held: padHeld, seen: padSeen, aim: gunAim, lastShot: gunLastShot, now: performance.now(), mode: mode, armed: !!playerGun, input: { left: input.left, right: input.right, up: input.up, down: input.down, sprint: input.sprint } }; },
    fakePad: function(gp){ window.__pgFakePad = gp; },
    levelType: function(v){ if (v) worldSettings.levelType = v; return worldSettings.levelType; },
    rules: function(o){ if (o) for (var k in o) worldSettings[k] = o[k]; return { lives: worldSettings.lives, timeLimit: worldSettings.timeLimit, fallLine: worldSettings.fallLine, knockouts: worldSettings.knockouts }; },
    run: function(){ return { lives: playRun.lives, deaths: playRun.deaths, left: runTimeLeft(), over: playRun.over, livesHud: document.getElementById("livesHud").hidden ? null : document.getElementById("livesHud").textContent, timeHud: document.getElementById("timeHud").hidden ? null : document.getElementById("timeHud").textContent }; },
    die: function(){ playerDied("test"); },
    runClock: function(ms){ playRun.t0 = performance.now() - ms; },
    askType: function(){ askLevelType(function(){}); return !typeOverlay.hidden; },
    pickType: function(id){ var b = Array.from(document.querySelectorAll('#typeCards .typeCard')).filter(function(c){ return c.textContent.indexOf(id) >= 0; })[0]; if (b) b.click(); return b ? true : false; },
    charScale: function(){ return charScale; },
    setCharSize: function(v){ worldSettings.charSize = v; },
    leaveHudShown: function(){ return !document.getElementById("leaveHud").hidden; },
    myWorld: function(){ openMyWorld(); return { hub: levelIsHubNow(), id: localLevelId, mode: mode }; },
    isHub: function(){ return levelIsHubNow(); },
    doorVisit: function(){ return doorVisit ? { name: doorVisit.name, at: doorVisit.at, ids: doorVisit.ids } : null; },
    enterDoor: function(id){ var g = gadgetById(id); if (!g) return false; enterDoor(g); return true; },
    leaveDoor: function(){ leaveDoor(); },
    interact: function(){ var dn = doorNearPlayer(); if (dn){ enterDoor(dn); return "door"; } return useLever() ? "lever" : null; },
    levelName: function(){ return document.getElementById("levelNameInput").value; },
    complete: function(){ levelComplete(); },
    glueAt: function(x, y){ handleGlueClick({ x: x, y: y }); return glueFirst ? glueFirst.id : null; },
    glueOf: function(id){ var o = objects.filter(function(x){ return x.id === id; })[0]; return o ? { glue: o.glue || null, mates: glueMates(o).map(function(m){ return m.id; }), held: gluedToScenery(o), isStatic: o.body.isStatic, layer: o.layer } : null; },
    unglue: function(id){ var o = objects.filter(function(x){ return x.id === id; })[0]; if (!o) return false; unglue(o); return true; },
    selIds: function(){ return selList().map(function(o){ return o.id; }); },
    emitterUseMissile: function(id){ var g = gadgetById(id); if (!g) return false; g.fireKind = "bullet"; g.ammoDef = normalizeProjDef(MISSILE_DEF); g.emit = null; return true; },
    bangs: function(){ return { holes: holesSeen, scorches: scorchesSeen, breaks: breaksSeen, crushes: crushesSeen }; },
    scorches: function(){ return gadgets.filter(function(g){ return g.scorch; }).length; },
    rocketOn: function(id){ var g = gadgetById(id); return !!(g && g.firing); },
    flingObj: function(id, vx, vy, w){ var o = objects.filter(function(x){ return x.id === id; })[0]; if (!o) return false; Body.setVelocity(o.body, { x: vx, y: vy }); if (w != null) Body.setAngularVelocity(o.body, w); return true; },
    objVel: function(id){ var o = objects.filter(function(x){ return x.id === id; })[0]; if (!o) return null; return { vx: o.body.velocity.x, vy: o.body.velocity.y, w: o.body.angularVelocity, x: o.body.position.x, y: o.body.position.y }; },
    beams: function(){ return gunBeams.length; },
    impacts: function(){ return { seen: impactsSeen, lastX: lastImpactAt ? lastImpactAt.x : null, live: sprites.filter(function(q){ return q.frames; }).length }; },
    projFlight: function(){ return objects.filter(function(o){ return o.projectile; }).map(function(o){ return { id: o.id, name: o.projectile.name, life: o.projectile.life, grav: o.projectile.grav, breaks: o.projectile.breaks, hurts: o.projectile.hurts, hit: o.projectile.hit }; }); },
    glowOf: function(id){ var o = objects.filter(function(x){ return x.id === id; })[0]; if (!o) return null; var g = objectGlow(o); return g ? { w: g.box.w, h: g.box.h, reach: g.reach, px: g.cv.width * g.cv.height } : null; },
    spots: function(){ return spotLights().map(function(s){ return { x: s.x, y: s.y, dir: s.dir, half: s.half, reach: s.reach, color: s.color, on: true }; }); },
    lightAt: function(sx, sy){ var d = ctx.getImageData(Math.round(sx * dpr), Math.round(sy * dpr), 1, 1).data; return { r: d[0], g: d[1], b: d[2], lum: (d[0] * 0.3 + d[1] * 0.59 + d[2] * 0.11) }; },
    moverDraft: function(){ return moverDraft ? moverDraft.id : null; },
    removeGadget: function(id){ var g = gadgetById(id); if (!g) return false; removeGadget(g); clearSelection(); return true; },
    moverChoose: function(id){ var g = gadgetById(id); if (!g) return false; moverDraft = g; return true; },
    menuPos: function(){ return { left: personalMenuEl.style.left, top: personalMenuEl.style.top, held: pmHeld }; },
    music: function(){ var m = worldSettings.music; return m ? { bpm: m.bpm, bars: m.bars, vol: m.vol, on: m.on, counts: MUSIC_TRACKS.map(function(t){ return m.tracks[t].length; }), tracks: JSON.parse(JSON.stringify(m.tracks)) } : null; },
    musicNew: function(){ worldSettings.music = newMusic(); return true; },
    musicSet: function(k, v){ if (worldSettings.music) worldSettings.music[k] = v; },
    musicNote: function(track, step, row, on){ var m = worldSettings.music; if (!m) return false; var a = m.tracks[track]; var i = a.findIndex(function(n){ return n[0] === step && n[1] === row; }); if (on && i < 0) a.push([step, row]); if (!on && i >= 0) a.splice(i, 1); return true; },
    musicPlay: function(v){ if (v) musicStart("page"); else musicStop(); return musicPlayer.playing; },
    musicState: function(){ return { playing: musicPlayer.playing, step: musicPlayer.step, source: musicPlayer.source, logged: musicLog.length, log: musicLog.slice(-16) }; },
    musicTrack: function(t){ if (t) musicTrack = t; return musicTrack; },
    musicGridRect: function(){ if (!musicGridEl) return null; var r = musicGridEl.getBoundingClientRect(); return { x: r.left, y: r.top, w: r.width, h: r.height }; },
    savedObjectsFull: function(){ return savedObjects.map(function(s){ return { id: s.id, name: s.name, gadgets: (s.gadgets || []).map(function(g){ return { kind: g.kind, x: g.x, y: g.y, text: g.text, mode: g.mode, color: g.color, hasWeak: !!g.weak, hasArt: !!g.art }; }), wires: s.wires || [] }; }); },
    stamp: function(id, x, y){ stampObject(id, { x: x, y: y }); return objects.length; },
    lastSound: function(){ return lastLevelSound; },
    drawTimed: function(n){ var t0 = performance.now(); for (var i = 0; i < n; i++) drawFrame(performance.now()); return (performance.now() - t0) / n; },
    stepTimed: function(n){ var t0 = performance.now(); for (var i = 0; i < n; i++) Engine.update(engine, MATTER_DELTA); return (performance.now() - t0) / n; },
    perfHud: function(v){ showPerf = !!v; return { avg: perfAvg, worst: perfWorst, draw: perfDrawMs, steps: perfLastSteps }; },
    bgDraft: function(){ openBackgroundDraft(null); },
    bgEdit: function(i){ openBackgroundDraft((mySkins.background || [])[i || 0] || null); },
    myBackgrounds: function(){ return (mySkins.background || []).map(function(e){ return { id: e.id, name: e.name, strokes: (e.data && e.data.art || []).length }; }); },
    useBackground: function(id){ var e = (mySkins.background || []).filter(function(x){ return x.id === id; })[0]; useBackground(e || null); },
    bg: function(){ return worldSettings.bg ? { id: worldSettings.bg.id, name: worldSettings.bg.name, strokes: worldSettings.bg.art.length } : null; },
    bgPlain: function(v){ if (v !== undefined) worldSettings.bgPlain = v; return worldSettings.bgPlain; },
    bgSlide: function(v){ if (v != null) worldSettings.bgSlide = v; return worldSettings.bgSlide; },
    pixel: function(sx, sy){ var d = ctx.getImageData(Math.round(sx * dpr), Math.round(sy * dpr), 1, 1).data; return [d[0], d[1], d[2], d[3]]; },
    tip: function(){ return tipShowing; },
    tipPending: function(){ return tipQueue[0] || null; },
    tipQueue: function(){ return tipQueue.slice(); },
    tipsClear: function(){ clearTips(); },
    tipsSeen: function(){ return Object.keys(tipsSeen); },
    tipsOn: function(v){ if (v != null) setTipsOn(v); return tipsOn; },
    tipsReset: function(){ resetTips(); },
    tipOk: function(){ hideTip(); },
    openSettings: function(){ openPauseMenu(); pauseView = "settings"; renderPauseMenu(); return pauseOverlay.textContent; },
    closePause: function(){ closePauseMenu(); },
    tipsTable: function(){ return TIPS; },
    thumb: function(){ return levelThumb(); },
    lastThumb: function(){ return lastThumb; },
    doSave: function(){ doSave(); },
    localLevels: function(){ return localLevels(); },
    saveLocal: function(d){ return saveLocalLevel(d); },
    setLevelIds: function(c, l){ setLevelIds(c, l); },
    storageUsed: function(){ return storageUsed(); },
    levelIds: function(){ return { cloud: cloudLevelId, local: localLevelId }; },
    openLoad: function(){ openLoad(); },
    respawn: function(){ respawnPlayer(); },
    minimap: function(){ return { hidden: minimapEl.hidden, on: minimapOn, frame: minimapFrame }; },
    gun: function(){ return playerGun ? { mode: playerGun.mode, left: playerGun.left, ammo: playerGun.ammo, name: playerGun.def ? playerGun.def.name : (playerGun.obj ? playerGun.obj.name : null) } : null; },
    fire: function(x, y){ gunLastShot = 0; gunFire({ x: x, y: y }); return playerGun ? playerGun.left : null; },
    projectiles: function(){ return objects.filter(function(o){ return o.projectile; }).map(function(o){ return { id: o.id, pos: { x: Math.round(o.body.position.x), y: Math.round(o.body.position.y) }, vel: { x: +o.body.velocity.x.toFixed(2), y: +o.body.velocity.y.toFixed(2) }, hit: o.projectile.hit }; }); },
    projDraft: function(){ openProjectileDraft(); return !charEditorOverlay.hidden; },
    myProjectiles: function(){ return (mySkins.projectile || []).map(function(e){ return { id: e.id, name: e.name, speed: e.data.speed, grav: e.data.grav }; }); },
    gunUseProjectile: function(id, entryId){ var g = gadgetById(id), e = (mySkins.projectile || []).find(function(x){ return x.id === entryId; }); if (!g || !e) return false; g.mode = "custom"; g.ammoDef = normalizeProjDef(e.data); return true; },
    emitterUseProjectile: function(id, entryId){ var g = gadgetById(id); if (!g) return false; if (entryId === "bullet"){ g.ammoDef = normalizeProjDef(BULLET_DEF); g.emit = null; return true; } var e = (mySkins.projectile || []).find(function(x){ return x.id === entryId; }); if (!e) return false; g.ammoDef = normalizeProjDef(e.data); g.emit = null; return true; },
    emitNow: function(id){ var g = gadgetById(id); if (!g) return 'nog'; g.pos = gadgetWorld(g); var r = emitObjectFrom(g); return r ? r.id : 'null:' + JSON.stringify({ ammo: !!g.ammoDef, emit: !!g.emit, pos: g.pos }); },
    emitState: function(id){ var g = gadgetById(id); return { nextAt: g.nextAt, total: g.total, alive: emittedAlive(g), input: g.input, wasOn: g.wasOn, maxAlive: g.maxAlive, maxTotal: g.maxTotal, pulse: g.pulse }; },
    emitted: function(){ return objects.filter(function(o){ return o.emitted; }).map(function(o){ return { id: o.id, by: o.emitted.by, pos: { x: Math.round(o.body.position.x), y: Math.round(o.body.position.y) }, vel: { x: +o.body.velocity.x.toFixed(2), y: +o.body.velocity.y.toFixed(2) } }; }); },
    myMats: function(){ return myMats.map(function(id){ var d = customMats[id]; return { id: id, name: d.name, tilePx: d.tilePx, friction: d.friction, restitution: d.restitution, density: d.density, grabbable: d.grabbable, hazard: d.hazard, floats: d.floats }; }); },
    matSet: function(id, props){ var d = customMats[id]; if (!d) return false; for (var k in props) d[k] = props[k]; customMatChanged(id); persistMyMats(); return true; },
    matForget: function(id){ myMats = myMats.filter(function(x){ return x !== id; }); persistMyMats(); },
    matKnown: function(id){ return !!customMats[id]; },
    matColour: function(id){ var r = matOf(id); return r ? r.color : null; },
    stickers: function(){ return (mySkins.sticker || []).map(function(s){ return { id: s.id, name: s.name }; }); },
    pickSticker: function(id){ var e = (mySkins.sticker || []).find(function(s){ return s.id === id; }); if (!e) return false; stickerPick = e; currentTool = "sticker"; canvas.dataset.tool = "sticker"; return true; },
    stickerHitAt: function(x, y){ var g = gadgetAt(x, y); return g ? g.id : null; },
    objAlpha: function(id, v){ var o = objects.find(function(o){ return o.id === id; }); if (!o) return null; if (v != null) o.alpha = v; return o.alpha == null ? 1 : o.alpha; },
    peekObj: function(){ return peekObj ? peekObj.id : null; },
    peek: function(v){ if (v != null && !!v !== layerPeek) togglePeek(); return layerPeek; },
    layerAlpha: function(l){ return layerDepth(l).a; },
    enclosedArea: function(x, y){ var r = enclosedRegionAt(x, y, buildLayer); return r ? Math.round(Math.abs(pgArea(r))) : 0; },
    enclosedAreaOn: function(x, y, l){ var r = enclosedRegionAt(x, y, l); return r ? Math.round(Math.abs(pgArea(r))) : 0; },
    clear: function(){ clearAllObjects(); clearWater(); }, starter: starterLevel,
    stats: function(){
      return objects.map(function(o){
        return { id:o.id, layer:o.layer, pieces:o.pieces.map(function(p){ return p.m+':'+pgVertexCount(p.poly)+'v/'+p.poly.length+'i'; }),
                 rings:o.pieces.map(function(p){ return p.poly.map(function(pl){ return pl.length; }); }),
                 parts:o.parts.length, corners:objCorners(o), static:o.body.isStatic, area:Math.round(objArea(o)),
                 alpha:o.alpha == null ? 1 : o.alpha,
                 areaBy:o.pieces.reduce(function(acc,p){ var k = p.m.split(':')[0]; acc[k] = (acc[k]||0) + Math.abs(pgArea(p.poly)); return acc; }, {}),
                 pos:{x:Math.round(o.body.position.x),y:Math.round(o.body.position.y)}, angle:+o.body.angle.toFixed(3),
                 bounds:{x:Math.round(o.body.bounds.min.x),y:Math.round(o.body.bounds.min.y),x2:Math.round(o.body.bounds.max.x),y2:Math.round(o.body.bounds.max.y)}, sensor:!!o.body.isSensor };
      });
    },
    regionAt: regionAt, objectAt: objectAt,
    selected: function(){ return selected; }, selectedRegion: function(){ return selectedRegion; },
    select: function(o){ selectObject(o); },
    anchor: function(){ anchorSelected(); },
    detachRegion: function(){ detachSelectedRegion(); },
    bolts: function(){ return bolts.map(function(b){ var wp = boltWorldPoint(b); return { id:b.id, x:Math.round(wp.x), y:Math.round(wp.y),
      a:b.objA?b.objA.id:null, b:b.objB?b.objB.id:null, mode:b.mode, layer:b.layer, speed:b.speed, tightness:b.tightness,
      kind:b.kind, dir:b.dir, strength:b.strength, angle:b.angle, period:b.period, visible:b.visible, limit:b.limit, minA:b.minA, maxA:b.maxA }; }); },
    flip: function(){ flipSelected(); },
    boltAt: function(x,y){ var bl = placeBoltAt({x:x,y:y}); return bolts.length; },
    boltSet: function(id, props){ var b = bolts.filter(function(q){ return q.id===id; })[0]; if (!b) return false;
      if (props.kind) setBoltKind(b, props.kind);
      for (var k in props){ if (k === 'kind') continue; if (k === 'stiffness' || k === 'damping') b.constraint[k] = props[k]; else b[k] = props[k]; }
      applyBoltMode(b); return true; },
    boltPairAt: function(x, y){ var pr = boltPairAt(x, y); return pr ? { front: pr.front.id, partner: pr.partner.id, layer: pr.layer } : null; },
    boltRel: function(id){ var b = bolts.filter(function(q){ return q.id===id; })[0]; return b ? +(relAngle(b)*180/Math.PI).toFixed(1) : null; },
    fling: function(vx, vy){ if (player) Body.setVelocity(player, { x:vx, y:vy }); },
    worldSize: function(){ return { w: WORLD_W, h: WORLD_H }; },
    view: function(){ return { x: camX, y: camY, w: viewRectW / camScale, h: viewRectH / camScale, zoom: camZoom }; },
    boltGap: function(id){ var b = bolts.filter(function(q){ return q.id===id; })[0]; if (!b || !b.constraint) return null;
      var pa = toWorldPoint(b.constraint.bodyA, b.constraint.pointA), pb = toWorldPoint(b.constraint.bodyB, b.constraint.pointB);
      return +Math.hypot(pa.x-pb.x, pa.y-pb.y).toFixed(2); },
    paused: function(v){ if (v != null) setPaused(!!v); return !runner.enabled; },
    engineSet: function(k, v){ engine[k] = v; return engine[k]; },
    timing: function(){ return { lastDelta: engine.timing.lastDelta, timeScale: engine.timing.timeScale, runnerDelta: runner.delta, isFixed: runner.isFixed, fps: runner.fps, dh: (runner.deltaHistory||[]).slice(-5) }; },
    stepRate: function(ms){ return new Promise(function(res){ var n = 0, f = function(){ n++; }; Events.on(engine, 'afterUpdate', f); setTimeout(function(){ Events.off(engine, 'afterUpdate', f); res(n * 1000 / ms); }, ms); }); },
    gadgets: function(){ return gadgets.map(function(g){ var wp = gadgetWorld(g); return { id:g.id, kind:g.kind, x:Math.round(wp.x), y:Math.round(wp.y), layer:g.layer,
      out:g.out, on:g.on, radius:g.radius, size:g.size, sticky:g.sticky, springs:g.springs, visible:g.visible, obj:g.obj?g.obj.id:null, input:g.input, scale:g.scale||1,
      zoom:g.zoom, tracking:g.tracking, speed:g.speed, hold:g.hold, holdMode:g.holdMode, holdForever:g.holdForever, once:g.once, shake:g.shake, freeze:g.freeze, sweep:g.sweep ? { dx:g.sweep.dx, dy:g.sweep.dy, zoom:g.sweep.zoom, secs:g.sweep.secs } : null,
      zone:g.zone ? { dx:g.zone.dx, dy:g.zone.dy, w:g.zone.w, h:g.zone.h } : null, view:g.view ? { dx:g.view.dx, dy:g.view.dy } : null,
      line:g.line ? { dx:g.line.dx, dy:g.line.dy } : null, bounce:g.bounce, u:g.u, home:g.home,
      setLight:g.setLight, light:g.light, setWater:g.setWater, water:g.water, secs:g.secs, latch:g.latch, latched:g.latched,
      range:g.range, fly:g.fly, deadly:g.deadly, weakMode:g.weakMode, color:g.color, look:g.look, weakArea: g.weak ? +Math.abs(pgArea(g.weak)).toFixed(1) : 0, dangerArea: g.danger ? +Math.abs(pgArea(g.danger)).toFixed(1) : 0,
      width: g.width, reach: g.reach, strength: g.strength, rot: g.rot, flipX: g.flipX,
      label: g.label, analog: g.analog, touching: g.touching, playerOnly: g.playerOnly, requireTag: g.requireTag, tagColor: g.tagColor, target: g.target, mode: g.mode, count: g.count, time: g.time, level: g.level, inputReset: g.inputReset,
      emitName: g.emit ? g.emit.name : null, freq: g.freq, maxAlive: g.maxAlive, maxTotal: g.maxTotal, pulse: g.pulse, total: g.total,
      ammoName: g.ammoDef ? g.ammoDef.name : null, ammo: g.ammo, hitUntil: g.hitUntil,
      text: g.text, showing: g.showing, said: g.said, explode: g.explode, blast: g.blast, sound: g.sound, pitch: g.pitch, every: g.every, state: g.state, inN: g.inN, inOn: g.inOn, cone: g.cone, bright: g.bright,
      firing: g.firing, strength: g.strength, angle: g.angle, leadsTo: g.leadsTo || null, targetName: g.targetName, fireKind: g.fireKind, pgrav: g.pgrav, plife: g.plife, pbreaks: g.pbreaks, phurts: g.phurts, hits: g.hits, hitCount: g.count, fires: g.fires, only: g.only, useZone: g.useZone, useSpots: g.useSpots, destroy: g.destroy, spotArea: g.kind === 'projsensor' && g.weak ? +Math.abs(pgArea(g.weak)).toFixed(1) : 0,
      hasSkin: !!(g.skin && skinHasArt(g.skin)), actionMode: g.actionMode, ghost: g.ghost, face: g.face, rate: g.rate, pspeed: g.pspeed, life: g.life, psize: g.psize,
      alpha: g.alpha, drawnFacing: g.drawnFacing, dying: g.dying, art: g.art ? { x:g.art.x, y:g.art.y, w:g.art.w, h:g.art.h } : null, hitStrokes: g.hitbox ? g.hitbox.length : 0 }; }); },
    skinStudioAt: function(id, step){ var g = gadgetById(id); if (!g) return false; openSkinStudio(g, step); return !charEditorOverlay.hidden; },
    refreshHost: function(id){ var g = gadgetById(id); if (g && g.obj) refreshObjectPhysics(g.obj); return !!g; },
    skinStudio: function(id){ var g = gadgetById(id); if (!g) return false; openSkinStudio(g); return !charEditorOverlay.hidden; },
    skinState: function(id){ var g = gadgetById(id); return g ? skinStateFor(g) : null; },
    sprites: function(){ return sprites.length; },
    skinOf: function(id){ var g = gadgetById(id); return g && g.skin ? packSkin(g.skin) : null; },
    setSkin: function(id, sk){ var g = gadgetById(id); if (!g) return false; g.skin = normalizeSkin(sk, g.kind); return true; },
    maskPaint: function(){ return maskPaint ? { g: maskPaint.g.id, kind: maskPaint.kind } : null; },
    beginMask: function(id, kind){ var g = gadgetById(id); if (!g) return false; selectGadget(g); beginMaskPaint(g, kind); return true; },
    endMask: function(){ endMaskPaint(); },
    liveWorld: function(){ return { light: liveLight(), water: liveWater() }; },
    moverDraft: function(){ return moverDraft ? moverDraft.id : null; },
    flying: function(){ return flying; },
    studio: function(cmd, a, b){
      if (cmd === 'open'){ openCharEditor(); return !charEditorOverlay.hidden; }
      if (cmd === 'close'){ closeCharEditor(); return charEditorOverlay.hidden; }
      if (cmd === 'drawing'){ return JSON.parse(JSON.stringify(ceTargetDrawing())); }
      if (cmd === 'where'){ return { state: pmEditState, frame: pmEditFrame, frames: ceFramesOf(pmEditState).length, mode: charMode, tool: ceTool, color: pmPaintColor, symmetry: ceSymmetry, zoom: +ceZoom.toFixed(3), playing: cePlaying, fps: charFps[pmEditState] }; }
      if (cmd === 'go'){ pmEditState = a; pmEditFrame = b || 0; renderCharEditorPanels(); ceLayout(); return true; }
      if (cmd === 'canvasRect'){ var r = ceCanvas.getBoundingClientRect(); return { x: r.left, y: r.top, w: r.width, h: r.height }; }
      if (cmd === 'chips'){ return Array.from(ceModeRowEl.querySelectorAll('button')).map(function(b){ return b.textContent; }); }
      if (cmd === 'click'){ var btn = Array.from(charEditorOverlay.querySelectorAll('button')).find(function(x){ return x.textContent.trim() === a; }); if (btn){ btn.click(); return true; } return false; }
      if (cmd === 'size'){ if (ceSubject.setSize) ceSubject.setSize(a, b); renderCharEditorPanels(); ceLayout(); return ceSubject.g ? { w: ceSubject.g.art.w, h: ceSubject.g.art.h } : null; }
      if (cmd === 'cursor'){ return ceCursor ? { x: +ceCursor.x.toFixed(3), y: +ceCursor.y.toFixed(3) } : null; }
      if (cmd === 'history'){ return { undo: ceHistory.undo.length, redo: ceHistory.redo.length }; }
      if (cmd === 'setColor'){ pmPaintColor = a; return pmPaintColor; }
      if (cmd === 'set'){ if (a === 'tool') ceTool = b; if (a === 'symmetry') ceSymmetry = !!b; if (a === 'opacity') ceOpacity = b; if (a === 'smooth') ceSmooth = !!b; if (a === 'brush') ceBrushW = b; renderCharEditorPanels(); return true; }
      return null;
    },
    menu: function(section, page){ if (section === null){ closePersonalMenu(); return false; } pmActiveSection = section; pmActivePage = page || null; openPersonalMenu(); return pmOpen; },
    camShot: function(id){ var g = gadgetById(id); return g && g.kind === 'camera' ? cameraShotRect(g) : null; },
    edCam: function(){ return edCam ? { zoom: edCam.zoom } : null; },
    camEdit: function(){ return { held: camEditHeld, left: Math.round(camEditUntil - performance.now()), wanted: worldPagePreviewWanted(), section: pmActiveSection, open: pmOpen }; },
    worldSet: function(k, v){ worldSettings[k] = v; applyWorldSettings(); return worldSettings[k]; },
    worldGet: function(k){ return worldSettings[k]; },
    camFollowing: function(){ return camFollow; },
    playCam: function(){ return { active: playCam.active ? playCam.active.id : null, easing: playCam.easing, cx: playCam.cx, cy: playCam.cy, zoom: playCam.zoom }; },
    mode: function(){ return mode; },
    s2wPage: function(px, py){ return screenToWorld(px, py); },
    nearLever: function(){ var g = leverNearPlayer(); return g ? g.id : null; },
    links: function(){ return links.map(function(l){ var e = linkEnds(l); return { id:l.id, kind:l.kind, a:l.objA.id, b:l.objB.id, ax:Math.round(e.a.x), ay:Math.round(e.a.y), bx:Math.round(e.b.x), by:Math.round(e.b.y),
      layer:l.layer, min:l.min, max:l.max, time:l.time, pause:l.pause, stiff:l.stiff, flipper:l.flipper, going:l.going, len:+l.len.toFixed(1), length:l.length, visible:l.visible, input:l.input,
      span:+Math.hypot(e.b.x-e.a.x, e.b.y-e.a.y).toFixed(1), segs:l.segs?l.segs.length:0 }; }); },
    linkAt: function(x,y){ placeLinkAt({x:x,y:y}); return links.length; },
    linkDraft: function(){ return linkDraft ? linkDraft.obj.id : null; },
    linkSet: function(id, props){ var l = linkById(id); if (!l) return false; for (var k in props){ if (k === 'length'){ setRopeLength(l, props[k]); } else if (k === 'stiff'){ setPistonStiff(l, !!props[k]); } else l[k] = props[k]; } return true; },
    ropePoints: function(id){ var l = linkById(id); return l && l.segs ? ropePoints(l).map(function(q){ return [Math.round(q.x), Math.round(q.y)]; }) : null; },
    selectLink: function(id){ var l = linkById(id); if (l){ selectLink(l); opWanted = true; renderSelBar(); } },
    linkDebug: function(id){ var l = linkById(id); if (!l || !l.constraint) return null; var c = l.constraint;
      return { A:{ x:+c.bodyA.position.x.toFixed(2), y:+c.bodyA.position.y.toFixed(2), ang:+c.bodyA.angle.toFixed(4), pt:[+c.pointA.x.toFixed(2), +c.pointA.y.toFixed(2)], angA:+(c.angleA||0).toFixed(4), st:c.bodyA.isStatic },
               B:{ x:+c.bodyB.position.x.toFixed(2), y:+c.bodyB.position.y.toFixed(2), ang:+c.bodyB.angle.toFixed(4), pt:[+c.pointB.x.toFixed(2), +c.pointB.y.toFixed(2)], angB:+(c.angleB||0).toFixed(4), st:c.bodyB.isStatic },
               ref: l.stiffRef ? { rod:+l.stiffRef.rodAng0.toFixed(4), base:+l.stiffRef.baseAng0.toFixed(4), rel:+l.stiffRef.relAng0.toFixed(4), tgtIsA:l.stiffRef.tgtIsA } : null, len:l.len }; },
    setFlying: function(v){ setFlying(!!v); return flying; },
    gadgetAt: function(x,y){ placeGadgetAt({x:x,y:y}); return gadgets.length; },
    gadgetSet: function(id, props){ var g = gadgetById(id); if (!g) return false; for (var k in props) g[k] = props[k]; return true; },
    wire: function(fromId, toId, port){ return addWire(gadgetById(fromId), receiverById(toId), port); },
    wires: function(){ return wires.slice(); },
    playerTo: function(x, y){ if (player){ Body.setPosition(player, {x:x,y:y}); Body.setVelocity(player, {x:0,y:0}); } },
    boltInput: function(id){ var b = boltById(id); return b ? b.input : undefined; },
    selectGadget: function(id){ var g = gadgetById(id); if (g){ selectGadget(g); opWanted = true; renderSelBar(); } },
    wiring: function(){ return wiring ? wiring.from.id : null; },
    boltGapTrue: function(id){ var b = bolts.filter(function(q){ return q.id===id; })[0]; if (!b || !b.constraint) return null;
      var c = b.constraint, pa = { x:c.bodyA.position.x + c.pointA.x, y:c.bodyA.position.y + c.pointA.y };
      var pb = { x:c.bodyB.position.x + c.pointB.x, y:c.bodyB.position.y + c.pointB.y };
      return { gap:+Math.hypot(pa.x-pb.x, pa.y-pb.y).toFixed(2), armAngleDeg:+(c.bodyB.angle*180/Math.PI).toFixed(1),
               drawnAt: boltWorldPoint(b), trueAt: pb }; },
    deselect: function(){ clearSelection(); },
    selection: function(){ return selList().map(function(o){ return o.id; }); },
    deleteRegion: function(r){ return deleteRegion(r); },
    duplicate: duplicateSelected, flip: flipSelected, rotate: rotateSelected,
    deleteSel: deleteSelected, layerSel: layerSelected, merge: mergeObjects,
    grabbing: function(){ return !!grabConstraint || !!carried; }, carrying: function(){ return carried ? carried.id : null; }, grab: function(v){ setGrabHeld(!!v); return !!grabConstraint || !!carried; },
    setGrabbable: function(id, v){ var o = objects.filter(function(q){ return q.id===id; })[0]; if (o) o.grabbable = v; return !!o; },
    grabTarget: function(){ var t = grabTarget(); return t ? { obj: t.obj.id, hold: t.hold } : null; },
    holdOverlap: function(){ var o = carried || (grabConstraint && grabConstraint.bodyB.plugin && grabConstraint.bodyB.plugin.obj); if (!o || !player || !o.body) return null;
      var cs = Query.collides(player, [o.body]), d = 0; cs.forEach(function(c){ if (c.depth > d) d = c.depth; }); return +d.toFixed(1); },
    playerVel: function(){ return player ? { x:+player.velocity.x.toFixed(2), y:+player.velocity.y.toFixed(2) } : null; },
    nudge: nudgeBrush, tool: function(){ return currentTool; },
    touching: function(poly,layer,reach){ return objectsTouching(poly,layer,reach); },
    waterInfo: function(){ return { count: waterCount, minRow: wMinRow, maxRow: wMaxRow }; },
    waterTimed: function(n){ var t0 = performance.now(); for (var i = 0; i < n; i++) stepWater(); var t1 = performance.now(); for (var j = 0; j < n; j++) rebuildWaterSolid(true); var t2 = performance.now();
      ctx.save(); for (var k = 0; k < n; k++) drawMaterialWater(); ctx.restore(); var t3 = performance.now();
      return { step: +((t1 - t0) / n).toFixed(2), solid: +((t2 - t1) / n).toFixed(2), draw: +((t3 - t2) / n).toFixed(2) }; },
    pour: function(x, y, r, amt){ addWaterAt(x, y, r, amt); return waterCount; },
    waterLevelAt: function(x, y){ var i = waterIndexAt(x, y); return i < 0 ? null : +waterLevels[i].toFixed(4); },
    waterTotal: function(){ var t = 0; for (var i = 0; i < WCELLS; i++) t += waterLevels[i]; return +t.toFixed(3); },
    spawnY: function(){ return checkpoints[0].y; },
    flags: function(){ return checkpoints.map(function(c){ return { x: c.x, y: c.y }; }); },
    addFlag: function(x, y){ checkpoints.push({ x: x, y: y, reached: false }); return checkpoints.length; },
    brush: function(){ return { shape: paintShape, r: paintRadius(), mode: paintMode, layer: buildLayer }; },
    bounds: function(id){ var o = objects.filter(function(q){ return q.id===id; })[0]; if(!o) return null;
      var b=o.body.bounds; return {x:+b.min.x.toFixed(2),y:+b.min.y.toFixed(2),x2:+b.max.x.toFixed(2),y2:+b.max.y.toFixed(2)}; },
    worldLight: function(v){ if (v != null){ worldSettings.light = v; if (!activeChanger()) worldLiveReset(); } return worldSettings.light; },
    matOf: matOf, matKey: matKey,
    setSolidLight: function(v){ var o = selList()[0] || objects[objects.length-1];
      o.lightSolid = !!v; rebuildFromPieces(o); if (objects.indexOf(o)>=0) refreshObjectPhysics(o); return o.id; },
    setLightFalls: function(v){ var o = selList()[0] || objects[objects.length-1];
      o.lightFalls = !!v; refreshObjectPhysics(o); return o.id; },
    lightState: function(){ var o = objects[objects.length-1];
      return { id:o.id, solid:!!o.lightSolid, falls:!!o.lightFalls, sensor:o.body.isSensor,
               still:o.body.isStatic, parts:o.parts.length, forced:!!o.forcedStatic }; },
    lightWorld: function(){ var o = objects.filter(function(q){ return q.allGlow; })[0]; if(!o) return null;
      var L = objectLights(o)[0]; var b=o.body, ca=Math.cos(b.angle), sa=Math.sin(b.angle);
      return { x: L.x*ca - L.y*sa + b.position.x, y: L.x*sa + L.y*ca + b.position.y }; },
    pixel: function(x, y){ var c = canvas.getContext('2d');
      var d = c.getImageData(Math.round(x*dpr), Math.round(y*dpr), 1, 1).data;
      return [d[0], d[1], d[2]]; },
    brightest: function(){ var c = canvas.getContext('2d');
      var d = c.getImageData(0,0,canvas.width,canvas.height).data, best=-1, bx=0, by=0;
      for (var i=0;i<d.length;i+=4){ var L=d[i]+d[i+1]+d[i+2]; if (L>best){best=L; var px=(i/4)|0; bx=px%canvas.width; by=(px/canvas.width)|0;} }
      return { x:+(bx/dpr).toFixed(1), y:+(by/dpr).toFixed(1), lum:best }; },
    playerPos: function(){ return player ? { x:player.position.x, y:player.position.y } : null; },
    playerSize: function(){ return { w: PW, h: PH, scale: charScale, art: charArt, parts: player ? player.parts.length : 0 }; },
    setCharScale: function(v){ setCharScale(v); return charScale; },
    setCharHit: function(strokes){ setCharHit(strokes); return { w: PW, h: PH, parts: player ? player.parts.length : 0 }; },
    objMass: function(id){ var o = objects.filter(function(q){ return q.id===id; })[0]; if (!o || !o.body) return null; var b = o.body; return b.isStatic ? (b._original ? b._original.mass : Infinity) : b.mass; },
    objWeight: function(id){ var o = objects.filter(function(q){ return q.id===id; })[0]; return o ? (o.weight == null ? 1 : o.weight) : null; },
    playerMass: function(){ return player ? player.mass : null; },
    openBox: function(id){ var o = objects.filter(function(q){ return q.id===id; })[0]; if (!o) return false; selectObject(o); opWanted = true; renderSelBar(); return !objPanelEl.hidden; },
    ctxOpen: function(){ return !objPanelEl.hidden; },
    holes: function(){ return objects.map(function(o){ return o.pieces.map(function(p){ return p.poly.map(function(pl){ return pl.slice(1).map(function(h){ return h.length; }); }); }); }); },
    undo: undo, redo: redo
  };
})();
</script>"""
old = "})();\n</script>"
assert s.count(old) == 1, s.count(old)
open('preview.html', 'w', encoding='utf-8').write(s.replace(old, HOOK))
print("preview.html", len(s))
